name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: make install
    - name: Run Application
      run: |
        make run &
        sleep 10
    - name: Check Application
      run: |
        curl -I http://localhost:3000
